### ISSUE TITLE
KeyError 'Upscalers' (WSL2 Network Error)

### ISSUE THREAD

**Issue by Kyxsune** [Interpause/auto-sd-krita#14]
Full Disclosure this is a weird use case, but I thought it would work after looking at the settings.

**Describe the bug**
Fails when attempting to connect to webui on port 7860

**To Reproduce**
1. Prime Automatic1111/stable-diffusion-webui on wsl2
2. Install Krita on Windows.
3. Set the Backend Url to the url given from launch.py on wsl2 (http://127.0.0.1:7860) s

**Expected behavior**
Detection and API calls done to the ports on local host

**Screenshots**
![image](https://user-images.githubusercontent.com/5920818/195251348-432a0e1e-6cd5-49cc-8ff1-d56f8932b43f.png)

**Desktop (please complete the following information):**
 - OS: Windows with WSL2 (Ubuntu 20.04)
 - Browser: Chrome
 - Krita 5.1.1
 - Commit: f5adaa0c8ccefab52c78f7ecfef9dd0e3ab17dd4

**Additional context**

If the port is set to a random one (ie 5000) it fails silently. If krita is closed while set to 7860 (the error source) then it will crash on startup.

No other SD plugins have been loaded into Krita.

My best guess is the query isn't reaching its destination. As the webui terminal shows no modifications
![image](https://user-images.githubusercontent.com/5920818/195252892-bf54802a-f294-4e7a-8416-775b3b8c44f5.png)

**Comment by Interpause** [comment]
Technically, WSL, like any virtual machine, is considered a separate computer. As such, you have to provide the `--listen` argument when starting up the WebUI/Backend to get it to work.

However, that will not be enough. The original plugin author sent the local file path of images instead of the images itself in the API. This means WSL would not work as the file path would be inside the virtual machine. I am planning to fix it this weekend, where I will have time to finally fully rewrite the API and the plugin's logic.

For now, you would have to install it locally using a venv or Conda environment unfortunately.

**Comment by Kyxsune** [comment]
Thanks for the explanation. I'm a novice when it comes to communication protocols and wasn't sure if it'd reach. :)
