### ISSUE TITLE
img2img always burns first image

### ISSUE THREAD

**Issue by Edgar-Nino** [Interpause/auto-sd-krita#27]
## Describe the bug
Hi, as the title says, img2img in krita always burns the first image, it seems as if it is trying to match the colors of the source image

after you use img2img in krita, all the first images start to burn in Stable Diffusion UI and Krita

if you don't use img2img in krita, the images don't burn

## To Reproduce
1. use img2img in krita

## Screenshots
**EDIT**: I attached a better example

### ORIGINAL SOURCE
![04656-1263979790](https://user-images.githubusercontent.com/61064699/197075485-f78c643e-c7d9-4d6c-b425-22f2d7649ed8.png)
### GRID BEFORE IMG2IMG IN KRITA SAME SEED
![grid-0225](https://user-images.githubusercontent.com/61064699/197075432-0c004c74-2db7-4ccb-b994-03300cd40738.png)
### GRID AFTER IMG2IMG IN KRITA SAME SEED
![grid-0228](https://user-images.githubusercontent.com/61064699/197075453-6003f9c5-b0d9-459b-8fc9-e6b13ab1ec6c.png)

## Desktop:
 - OS: Windows
 - Last commit version

## Additional context
I was using two embeddings and a merge of SD 1.4 and WD 1.3

**Comment by Interpause** [comment]
The burning is likely to be an upstream bug with img2img color correction. I'll look into it and submit a bug report if so.

Under the config tab, I set it to do color correction for img2img by default, so you can disable it there. The behaviour where it starts burning after using the Krita plugin is because the webUI & the plugin store their settings separately (i.e. color correction for img2img is off in the webUI).

I think I might decide to make color correction individually toggleable for img2img vs inpainting (where its more useful).

**Comment by Edgar-Nino** [comment]
Oh I was thinking that was the case with upstream, but it seemed strange to me that only the first image was modified
Thanks!!!

**Comment by Interpause** [comment]
btw, I also don't know why its occuring for specifically the first image. Internally, its a turn on/off sorta thing, so it might mean the upstream bug causes color correction to be applied only to the first image.
